#!/usr/bin/env sh
#
# Calling this script is equal to calling
#	export LD_LIBRARY_PATH="/usr/lib/jni" mvn
#
# This script adds the LD_LIBRARY_PATH option transparently, so that
# it is available from all call sites that call `mvn` from the PATH.
# The effect is that "/usr/lib/jni" is prepended to the dynamic library
# search path. Note that it can still be overridden in java with the
#	-Djava.library.path
# option.

# Get path to my install location
fullpathself=$(readlink -f "$0")

# Find actual `mvn` executable from $PATH
MVN=$(nextexec "${fullpathself}")

if [ -z "${MVN}" ] ; then
	>&2 echo "$(readlink -f "$0") Error: No underlying mvn found from PATH."
	exit 1
fi

export LD_LIBRARY_PATH="/usr/lib/jni"
exec "${MVN}" "$@"
