#!/usr/bin/env sh
#
# Calling this script is equal to calling
#	export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/lib/jni" mvn
#
# This script adds the LD_LIBRARY_PATH option transparently, so that
# it is available from all call sites that call `mvn` from the PATH.
# The effect is that "/usr/lib/jni" is prepended to the dynamic library
# search path. Note that it can still be overridden in java with the
#	-Djava.library.path
# option.

# Get path to my install location
fullpathself=$(readlink -f "$0")

# Get path to underlying 'mvn' executable from $PATH
mvn=$(nextexec "${fullpathself}")

# Resolve links so that it will work with user installed zip version
mvn=$(readlink -f "$mvn")

if [ -z "${mvn}" ] ; then
	>&2 echo "$(readlink -f "$0") Error: No underlying mvn found from PATH."
	exit 1
fi

libpath=""
if [ -z "${LD_LIBRARY_PATH}" ] ; then
	libpath="/usr/lib/jni"
else
	libpath="${LD_LIBRARY_PATH}:/usr/lib/jni"
fi

export LD_LIBRARY_PATH="${libpath}"
exec "${mvn}" "$@"
