#!/usr/bin/env sh

# This script wraps and modifies the behaviour of *java*
# it sets the LD_LIBRARY_PATH before execution

fullpathself=$(readlink -f $0)

JAVA=$(nextexec "$fullpathself")

export LD_LIBRARY_PATH="/usr/lib/jni"

$JAVA $@
