#!/usr/bin/env sh
#
# This script wraps and modifies the behaviour of *java*
# it sets the LD_LIBRARY_PATH before execution

# Get path to my install location
fullpathself=$(readlink -f $0)

# Find actual `java` executable from $PATH
JAVA=$(nextexec "$fullpathself")

if [ -z "$JAVA" ] ; then
	>&2 echo "$(readlink -f "${0}") Error: No underlying java found from PATH."
	exit 1
fi

exec env LD_LIBRARY_PATH="/usr/lib/jni" $JAVA "$@"
